/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.yudharta.kasir.ui;

import it.yudharta.kasir.ui.dialog.AturKoneksi;
import it.yudharta.kasir.ui.panel.DaftarBarang;

/**
 *
 * @author cahya
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MenuUtama() {
        initComponents();
    }

    public static MenuUtama getInstance() {
        return MenuUtamaHolder.INSTANCE;
    }

    private static class MenuUtamaHolder {

        private static final MenuUtama INSTANCE = new MenuUtama();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMaster = new javax.swing.JMenu();
        miDaftarBarang = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miAturKoneksi = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir");
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

        mnMaster.setMnemonic('M');
        mnMaster.setText("Master Data");

        miDaftarBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        miDaftarBarang.setText("Daftar Barang");
        miDaftarBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDaftarBarangActionPerformed(evt);
            }
        });
        mnMaster.add(miDaftarBarang);
        mnMaster.add(jSeparator1);

        miAturKoneksi.setText("Atur Koneksi");
        miAturKoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAturKoneksiActionPerformed(evt);
            }
        });
        mnMaster.add(miAturKoneksi);

        jMenuBar1.add(mnMaster);

        mnTransaksi.setText("Transaksi");
        jMenuBar1.add(mnTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miAturKoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAturKoneksiActionPerformed
        AturKoneksi dialog = new AturKoneksi(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_miAturKoneksiActionPerformed

    private void miDaftarBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDaftarBarangActionPerformed
        DaftarBarang daftarBarang = new DaftarBarang(panelUtama);
        this.panelUtama.add("Daftar Barang", daftarBarang);
    }//GEN-LAST:event_miDaftarBarangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miAturKoneksi;
    private javax.swing.JMenuItem miDaftarBarang;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JTabbedPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
